# Generated by Django 4.1.5 on 2023-01-12 09:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular card across whole cardSystem', primary_key=True, serialize=False)),
                ('date_of_last_use', models.DateField(blank=True, null=True)),
                ('card_number', models.CharField(help_text='Enter card number', max_length=20)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cardSystem.cardowner')),
            ],
            options={
                'ordering': ['-date_of_last_use'],
            },
        ),
    ]
