# Generated by Django 4.1.5 on 2023-01-12 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cardSystem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='author',
        ),
        migrations.AddField(
            model_name='card',
            name='card_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cardSystem.cardowner'),
        ),
    ]
