# Generated by Django 4.1.5 on 2023-01-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardSystem', '0002_remove_card_author_card_card_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='date_of_last_use',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
